spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/farmshop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  thymeleaf:
    cache: false

  file:
    upload:
      directory: ./uploads/images # 외부 경로로 지정
  # 정적 리소스 설정 추가
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace