spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/farmshop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  thymeleaf:
    cache: false

  file:
    upload:
      directory: ./uploads/images   # 업로드 루트

  web:
    resources:
      static-locations:
        - classpath:/static/        # 기존 스태틱
        - file:./uploads/
      cache:
        period: 0

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.thymeleaf: TRACE
    org.thymeleaf.parser: TRACE
